name: show-input-context
description: Show the input context of a GitHub Actions workflow run.

runs:
  using: "composite"
  steps:
    - name: show input context
      shell: bash
      run: |
        echo "::group::Input Context"
        echo "{{ toJson(inputs) }}" | jq -S .
        echo "::endgroup::"
