name: show-inputs-context
description: Show the inputs context of a GitHub Actions workflow run.

runs:
  using: "composite"
  steps:
    - name: show inputs context
      shell: bash
      run: |
        echo -e "Dumping context...\n"
        echo "::group::Inputs Context"
        echo "{{ toJson(inputs) }}" | jq -S .
        echo "::endgroup::"
