name: _purge_workflow_runs

on:
  schedule:
    - cron: '53 10 * * *' # run daily at 10:53 UTC
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  purge-workflow-runs:
    uses: ./.github/workflows/reusable_purge_workflow_runs.yaml
