name: _release

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/reusable_*.yaml'

  workflow_dispatch:
    inputs:
      bump:
        default: patch
        options:
          - patch
          - minor
          - major
        required: false
        type: choice

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/reusable_release.yaml
    with:
      bump: ${{ github.event.inputs.bump || 'patch' }}
