name: _release
run-name: "release: ${{ github.event_name == 'workflow_dispatch' && format('manual bump ({0})', github.event.inputs.bump) || github.event.head_commit.message }}"

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/reusable_*.yaml'

  workflow_dispatch:
    inputs:
      bump:
        default: patch
        options:
          - patch
          - minor
          - major
        required: false
        type: choice

permissions:
  contents: write

jobs:
  release:
    uses: ./.github/workflows/reusable_release.yaml
    with:
      bump: ${{ github.event.inputs.bump || 'patch' }}
