name: _request_copilot_review
run-name: "_request_copilot_review: ${{ github.event.pull_request.title }}"

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

permissions:
  pull-requests: write

jobs:
  reusable-request-copilot-review:
    uses: ./.github/workflows/reusable_request_copilot_review.yaml
    secrets:
      PAT_REQUEST_COPILOT_REVIEW: ${{ secrets.PAT_REQUEST_COPILOT_REVIEW }}
