name: reusable-purge-workflow-logs

on:
  workflow_call:
  workflow_dispatch:

permissions:
  actions: write
  contents: read

jobs:
  purge-workflow-logs:
    runs-on: ubuntu-24.04
    steps:
      - name: purge workflow logs
        uses: Mattraks/delete-workflow-runs@b3018382ca039b53d238908238bd35d1fb14f8ee # v2.1.0
        with:
          check_pullrequest_exist: true
          keep_minimum_runs: 3
          repository: ${{ github.repository }}
          retain_days: 7
          token: ${{ github.token }}
