name: reusable-linter
run-name: "reusable linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  workflow_call:
    inputs:
      actionlint:
        default: true
        required: false
        type: boolean
      shellcheck:
        default: true
        required: false
        type: boolean
      terraform-fmt:
        default: true
        required: false
        type: boolean
      terragrunt-hcl-fmt:
        default: true
        required: false
        type: boolean
      tflint:
        default: true
        required: false
        type: boolean
      trivy-config:
        default: true
        required: false
        type: boolean

  workflow_dispatch:
    inputs:
      actionlint:
        default: true
        required: false
        type: boolean
      shellcheck:
        default: true
        required: false
        type: boolean
      terraform-fmt:
        default: true
        required: false
        type: boolean
      terragrunt-hcl-fmt:
        default: true
        required: false
        type: boolean
      tflint:
        default: true
        required: false
        type: boolean
      trivy-config:
        default: true
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  # github action workflow linter
  actionlint:
    if: ${{ inputs.actionlint }}
    runs-on: ubuntu-latest
    steps:
      - &checkout_action
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: docker://rhysd/actionlint@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667 # v1.7.12
        with:
          args: -color

  # shell script linter
  shellcheck:
    if: ${{ inputs.shellcheck }}
    runs-on: ubuntu-latest
    steps:
      - *checkout_action
      - uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # v2.0.0
        with:
          scandir: .

  # terraform syntax linter
  terraform-fmt:
    if: ${{ inputs.terraform-fmt }}
    runs-on: ubuntu-latest
    steps:
      - *checkout_action
      - uses: docker://ghcr.io/ulfiac/terraform-fmt:v1.15.7@sha256:676662330f226b8b225d6177e240a760cf0c5c9d525e39a2de5ed977c9de2453
        with:
          args: -check -diff -recursive .

  # hcl syntax linter
  terragrunt-hcl-fmt:
    if: ${{ inputs.terragrunt-hcl-fmt }}
    runs-on: ubuntu-latest
    steps:
      - *checkout_action
      - uses: docker://ghcr.io/ulfiac/terragrunt-hcl-fmt:v1.0.8@sha256:b3c4c5002f9182f8c2607dd1839df07146e6f6980901a6c35b430a3d9d6688c6
        with:
          args: --check --diff .

  # terraform linter
  tflint:
    if: ${{ inputs.tflint }}
    runs-on: ubuntu-latest
    steps:
      - *checkout_action
      - uses: terraform-linters/tflint-load-config-action@32d9f74138340b95873e956fbdfc390db819bff1 # v3.0.0
        with:
          source-repo: ulfiac/commons
          source-path: .tflint.hcl
          source-ref: main
      - uses: terraform-linters/setup-tflint@6e1e0642c0289bd619021bf6b34e3c08ed1e005a # v6.3.0
      - run: tflint --version
      - run: tflint --init
      - run: tflint --version
      - run: tflint --recursive --color

  # security scanner
  trivy-config:
    if: ${{ inputs.trivy-config }}
    runs-on: ubuntu-latest
    steps:
      - *checkout_action
      - uses: aquasecurity/setup-trivy@81e514348e19b6112ce2a7e3ecbafe19c1e1f567 # v0.3.1
      - run: trivy --version
      - run: trivy config --exit-code 1 .
