name: reusable-linter
run-name: "reusable linter: ${{ github.event_name == 'pull_request' && github.event.pull_request.title || github.ref_name }}"

on:
  workflow_call:
    inputs:
      actionlint:
        default: true
        required: false
        type: boolean
      shellcheck:
        default: true
        required: false
        type: boolean
      terraform-fmt:
        default: true
        required: false
        type: boolean
      terragrunt-hcl-fmt:
        default: true
        required: false
        type: boolean
      tflint:
        default: true
        required: false
        type: boolean
      trivy-config:
        default: true
        required: false
        type: boolean

  workflow_dispatch:
    inputs:
      actionlint:
        default: true
        required: false
        type: boolean
      shellcheck:
        default: true
        required: false
        type: boolean
      terraform-fmt:
        default: true
        required: false
        type: boolean
      terragrunt-hcl-fmt:
        default: true
        required: false
        type: boolean
      tflint:
        default: true
        required: false
        type: boolean
      trivy-config:
        default: true
        required: false
        type: boolean

permissions:
  contents: read

jobs:
  # github action workflow linter
  actionlint:
    if: ${{ inputs.actionlint }}
    runs-on: ubuntu-latest
    steps:
      - &checkout_action
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      - uses: docker://rhysd/actionlint:1.7.12@sha256:b1934ee5f1c509618f2508e6eb47ee0d3520686341fec936f3b79331f9315667
        with:
          args: -color

  # shell script linter
  shellcheck:
    if: ${{ inputs.shellcheck }}
    runs-on: ubuntu-latest
    steps:
      - *checkout_action
      - uses: ludeeus/action-shellcheck@00cae500b08a931fb5698e11e79bfbd38e612a38 # 2.0.0
        with:
          scandir: .

  # terraform syntax linter
  terraform-fmt:
    if: ${{ inputs.terraform-fmt }}
    runs-on: ubuntu-latest
    steps:
      - *checkout_action
      - uses: docker://ghcr.io/ulfiac/terraform-fmt:1.15.7@sha256:3bcad26632958df272024c5933f3ad1e913143ef10d4147b5b50b761659d0f94
        with:
          args: -check -diff -recursive .

  # hcl syntax linter
  terragrunt-hcl-fmt:
    if: ${{ inputs.terragrunt-hcl-fmt }}
    runs-on: ubuntu-latest
    steps:
      - *checkout_action
      - uses: docker://ghcr.io/ulfiac/terragrunt-hcl-fmt:1.1.0@sha256:6d358378adb89f0434fb4ec2ffeac3ea186341c56a9d0ec73a299fe5624a70ab
        with:
          args: --check --diff .

  # terraform linter
  tflint:
    if: ${{ inputs.tflint }}
    runs-on: ubuntu-latest
    steps:
      - *checkout_action
      - uses: docker://ghcr.io/ulfiac/tflint:0.63.1@sha256:2084327e2d7b1e9060eb990cea017fe9b7cd86415e997e03a221632889cdd909
        with:
          args: --recursive --color

  # security scanner
  trivy-config:
    if: ${{ inputs.trivy-config }}
    runs-on: ubuntu-latest
    steps:
      - *checkout_action
      - uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        with:
          scan-type: config
          scan-ref: .
          exit-code: '1'
