name: reusable-request-copilot-review
run-name: "reusable request copilot review: ${{ github.event.pull_request.title }}"

on:
  workflow_call:
    secrets:
      PAT_REQUEST_COPILOT_REVIEW:
        required: true

permissions:
  pull-requests: write

jobs:
  request-copilot-review:
    if: github.event.pull_request.user.type == 'Bot'
    runs-on: ubuntu-24.04
    steps:
      - name: request copilot review
        env:
          GH_TOKEN: ${{ secrets.PAT_REQUEST_COPILOT_REVIEW }}
          GH_REPO: ${{ github.repository }}
        run: gh pr edit "${{ github.event.pull_request.number }}" --add-reviewer @copilot
